spring:
    config:
        import: optional:file:.env[.properties]
    application:
        name: matchday-server
    datasource:
        url: ${SPRING_TEST_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect

    flyway:
        enabled: false

    cloud:
        aws:
            s3:
                bucket: ${BUCKET_NAME}
            stack:
                auto: false
            region:
                static: ${AWS_REGION}
            credentials:
                access-key: ${AWS_ACCESS_KEY}
                secret-key: ${AWS_SECRET_KEY}

springdoc:
    api-docs:
        version: "openapi_3_0"
        url: "https://dev-api.matchday-planner.com"

decorator:
    datasource:
        p6spy:
            enable-logging: false

jwt:
    secret: ${JWT_SECRET}

oauth:
    google:
        client-id: ${OAUTH_GOOGLE_CLIENT_ID}
        client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
        redirect-url: ${OAUTH_GOOGLE_REDIRECT_URL}
    kakao:
        client-id: ${OAUTH_KAKAO_CLIENT_ID}